using System.Text;

namespace RobloxCS.Bindgen;

// Renders extracted modules to a C# binding file: static classes carrying [LuauModule]/[WallyPackage],
// members carrying [LuauName] when the Luau name isn't a usable C# identifier.
internal static class BindingEmitter
{
    public static string Emit(string ns, IReadOnlyList<LuauModule> modules)
    {
        var sb = new StringBuilder();
        sb.Append("// <auto-generated> Generated by rbxcs bindgen from Luau source. Do not edit by hand.\n");
        sb.Append("#nullable enable\n");
        sb.Append("using RobloxCS;\n\n");
        sb.Append("namespace ").Append(ns).Append(";\n");
        foreach (var m in modules)
        {
            sb.Append('\n');
            EmitModule(sb, m, 0);
        }
        return sb.ToString();
    }

    private static void EmitModule(StringBuilder sb, LuauModule m, int indent)
    {
        var pad = new string(' ', indent * 4);
        if (m.Kind == BindingKind.Wally)
            sb.Append(pad).Append("[WallyPackage(\"").Append(m.WallyAlias ?? m.CsName).Append("\")]\n");
        else if (m.BindingPath is not null)
            sb.Append(pad).Append("[LuauModule(\"").Append(m.BindingPath).Append("\")]\n");

        var kw = m.IsClass ? "public sealed class " : "public static class ";
        sb.Append(pad).Append(kw).Append(m.CsName).Append("\n").Append(pad).Append("{\n");

        var inner = new string(' ', (indent + 1) * 4);
        foreach (var mem in m.Members)
        {
            if (mem.Kind != MemberKind.Constructor && mem.LuauName != mem.CsName && mem.CsName.TrimStart('@') != mem.LuauName)
                sb.Append(inner).Append("[LuauName(\"").Append(mem.LuauName).Append("\")]\n");

            var stat = mem.IsStatic ? "static " : "";
            switch (mem.Kind)
            {
                case MemberKind.Constructor:
                    sb.Append(inner).Append("public ").Append(m.CsName).Append('(').Append(Params(mem)).Append(") { }\n");
                    break;
                case MemberKind.Method:
                    var body = mem.CsType == "void" ? "{ }" : "=> default!;";
                    sb.Append(inner).Append("public ").Append(stat).Append(mem.CsType).Append(' ')
                        .Append(mem.CsName).Append('(').Append(Params(mem)).Append(") ").Append(body).Append('\n');
                    break;
                default:
                    sb.Append(inner).Append("public ").Append(stat).Append(mem.CsType).Append(' ')
                        .Append(mem.CsName).Append(" => default!;\n");
                    break;
            }
        }

        foreach (var nested in m.Nested)
            EmitModule(sb, nested, indent + 1);

        sb.Append(pad).Append("}\n");
    }

    private static string Params(LuauMember mem) =>
        string.Join(", ", mem.Params.Select(p => (p.IsParams ? "params " : "") + p.CsType + " " + p.Name));
}
