<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <RootNamespace>RobloxCS.Bindgen</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Loretta.CodeAnalysis.Lua" Version="0.2.13" />
  </ItemGroup>

</Project>
