// <auto-generated> Generated by rbxcs bindgen from Luau source. Do not edit by hand.
#nullable enable
using RobloxCS;

namespace Vendor;

[LuauModule("Shared/Pkg")]
public static class Pkg
{
    [LuauModule("Shared/Pkg/MathX")]
    public static class MathX
    {
        public static double PI => default!;
        public static string name => default!;
        public static double add(double a, double b) => default!;
        public static double clamp(double v, double? lo, double? hi) => default!;
        public static double sum(params object[] args) => default!;
    }
    [LuauModule("Shared/Pkg/Store")]
    public static class Store
    {
        public static double? get(string key) => default!;
        public static string[] keys() => default!;
        public static System.Collections.Generic.Dictionary<string, double> map() => default!;
        public static Roblox.RBXScriptConnection on(System.Action<string> cb) => default!;
        public static object custom(object x) => default!;
    }
}
