// <auto-generated> Generated by rbxcs bindgen from Luau source. Do not edit by hand.
#nullable enable
using RobloxCS;

namespace Demo;

[WallyPackage("Signal")]
public sealed class Signal
{
    public Signal(string name) { }
    public static Signal wrap(Roblox.RBXScriptSignal rbx) => default!;
    public void Fire(params object[] args) { }
    public Roblox.RBXScriptConnection Connect(System.Action<object> fn) => default!;
    public void Destroy() { }
}
