using Microsoft.CodeAnalysis;

namespace RobloxCS.ApiGenerator;

// Incremental source generator: injects Roblox API C# stubs into the consumer compilation
// so user code type-checks and gets IntelliSense with no referenced Roblox.dll.
//
// ponytail: P0 hand-seeds a tiny surface via PostInitialization (static, perfectly cached).
// P3 swaps this for parsing the Roblox API Dump JSON shipped as an AdditionalFile.
[Generator]
public sealed class RobloxApiGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource("RobloxApi.g.cs", Stub));
    }

    private const string Stub = """
        // <auto-generated/>
        #nullable enable
        namespace Roblox
        {
            public class Instance
            {
                public string Name = "";
                public Instance? Parent;
            }

            public sealed class DataModel : Instance
            {
                public Instance GetService(string className) => default!;
            }

            public static class Globals
            {
                public static readonly DataModel game = default!;
                public static readonly Instance workspace = default!;
                public static void print(params object?[] args) { }
            }
        }
        """;
}
