using System.Net.Http;
using System.Text;
using System.Text.Json;

namespace RobloxCS.ApiGen;

// Usage:
//   RobloxCS.ApiGen --fetch <out.cs>          fetch the live API dump from Roblox, then generate
//   RobloxCS.ApiGen <api-dump.json> <out.cs>  generate from a local dump file
// Emits C# declarations for the whole Roblox class hierarchy + enums + datatypes into `namespace Roblox`.
internal static class Program
{
    private static async Task<int> Main(string[] args)
    {
        string json, outPath;
        if (args.Length >= 2 && args[0] == "--fetch")
        {
            json = await FetchDumpAsync();
            outPath = args[1];
        }
        else if (args.Length >= 2)
        {
            json = File.ReadAllText(args[0]);
            outPath = args[1];
        }
        else
        {
            Console.Error.WriteLine("usage: RobloxCS.ApiGen (--fetch | <api-dump.json>) <out.cs>");
            return 1;
        }

        File.WriteAllText(outPath, Generate(json));
        Console.WriteLine($"rbxcs apigen: wrote {outPath}");
        return 0;
    }

    // Replicates Roblox-API-Dump-Tool: the current Studio deploy hash comes from versionQTStudio,
    // then the dump is fetched from the versioned CDN path.
    private static async Task<string> FetchDumpAsync()
    {
        using var http = new HttpClient();
        var version = (await http.GetStringAsync("https://setup.rbxcdn.com/versionQTStudio")).Trim();
        Console.Error.WriteLine($"rbxcs apigen: Roblox Studio {version}");
        return await http.GetStringAsync($"https://setup.rbxcdn.com/{version}-API-Dump.json");
    }

    public static string Generate(string json)
    {
        using var doc = JsonDocument.Parse(json);
        var root = doc.RootElement;
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/> Roblox API surface generated from the API Dump.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("namespace Roblox;");
        sb.AppendLine();

        var known = CollectClassNames(root);
        var emitted = new HashSet<string>(DataTypeNames); // datatypes come from the const below

        if (root.TryGetProperty("Classes", out var classes))
            foreach (var c in classes.EnumerateArray())
            {
                var name = c.GetProperty("Name").GetString()!;
                if (emitted.Add(name))
                    EmitClass(sb, c, known);
            }

        if (root.TryGetProperty("Enums", out var enums))
            foreach (var e in enums.EnumerateArray())
            {
                var name = e.GetProperty("Name").GetString()!;
                if (emitted.Add(name))
                    EmitEnum(sb, e);
            }

        sb.Append(DataTypes);
        return sb.ToString();
    }

    // Roblox DataTypes are not part of the API Dump JSON (which has only Classes + Enums), so the
    // generator supplies them. Emitted as structs (value types) -> native Luau globals at transpile.
    private const string DataTypes = """

        // ---- Roblox DataTypes ----
        public struct Vector2
        {
            public float X { get; set; }
            public float Y { get; set; }
            public float Magnitude { get; set; }
            public Vector2 Unit => default!;
            public Vector2(float x, float y) { X = x; Y = y; Magnitude = default; }
            public float Dot(Vector2 other) => default!;
            public Vector2 Lerp(Vector2 to, float alpha) => default!;
        }

        public struct Vector3
        {
            public float X { get; set; }
            public float Y { get; set; }
            public float Z { get; set; }
            public float Magnitude { get; set; }
            public Vector3 Unit => default!;
            public Vector3(float x, float y, float z) { X = x; Y = y; Z = z; Magnitude = default; }
            public float Dot(Vector3 other) => default!;
            public Vector3 Cross(Vector3 other) => default!;
            public Vector3 Lerp(Vector3 to, float alpha) => default!;
        }

        public struct CFrame
        {
            public Vector3 Position { get; set; }
            public Vector3 LookVector { get; set; }
            public Vector3 RightVector { get; set; }
            public Vector3 UpVector { get; set; }
            public CFrame(float x, float y, float z) { Position = default; LookVector = default; RightVector = default; UpVector = default; }
            public CFrame(Vector3 position) { Position = position; LookVector = default; RightVector = default; UpVector = default; }
            public CFrame Inverse() => default!;
            public CFrame Lerp(CFrame to, float alpha) => default!;
            public Vector3 PointToWorldSpace(Vector3 v) => default!;
        }

        public struct Color3
        {
            public float R { get; set; }
            public float G { get; set; }
            public float B { get; set; }
            public Color3(float r, float g, float b) { R = r; G = g; B = b; }
            public Color3 Lerp(Color3 to, float alpha) => default!;
        }

        public struct UDim
        {
            public float Scale { get; set; }
            public int Offset { get; set; }
            public UDim(float scale, int offset) { Scale = scale; Offset = offset; }
        }

        public struct UDim2
        {
            public UDim X { get; set; }
            public UDim Y { get; set; }
            public UDim2(float xScale, int xOffset, float yScale, int yOffset) { X = default; Y = default; }
            public UDim2 Lerp(UDim2 to, float alpha) => default!;
        }

        public struct Rect
        {
            public Vector2 Min { get; set; }
            public Vector2 Max { get; set; }
            public float Width { get; set; }
            public float Height { get; set; }
            public Rect(Vector2 min, Vector2 max) { Min = min; Max = max; Width = default; Height = default; }
        }

        public struct Region3
        {
            public Vector3 CFrame { get; set; }
            public Vector3 Size { get; set; }
            public Region3(Vector3 min, Vector3 max) { CFrame = default; Size = default; }
        }

        public struct NumberRange
        {
            public float Min { get; set; }
            public float Max { get; set; }
            public NumberRange(float value) { Min = value; Max = value; }
            public NumberRange(float min, float max) { Min = min; Max = max; }
        }

        public struct BrickColor
        {
            public string Name { get; set; }
            public Color3 Color { get; set; }
            public int Number { get; set; }
            public BrickColor(int number) { Name = default!; Color = default; Number = number; }
        }

        public struct TweenInfo
        {
            public float Time { get; set; }
            public int RepeatCount { get; set; }
            public bool Reverses { get; set; }
            public TweenInfo(float time) { Time = time; RepeatCount = default; Reverses = default; }
        }

        public struct Ray
        {
            public Vector3 Origin { get; set; }
            public Vector3 Direction { get; set; }
            public Ray(Vector3 origin, Vector3 direction) { Origin = origin; Direction = direction; }
            public Vector3 ClosestPoint(Vector3 point) => default!;
        }

        public struct Vector2int16
        {
            public int X { get; set; }
            public int Y { get; set; }
            public Vector2int16(int x, int y) { X = x; Y = y; }
        }

        public struct Vector3int16
        {
            public int X { get; set; }
            public int Y { get; set; }
            public int Z { get; set; }
            public Vector3int16(int x, int y, int z) { X = x; Y = y; Z = z; }
        }

        public struct Region3int16
        {
            public Vector3int16 Min { get; set; }
            public Vector3int16 Max { get; set; }
            public Region3int16(Vector3int16 min, Vector3int16 max) { Min = min; Max = max; }
        }

        public struct DateTime
        {
            public long UnixTimestamp { get; set; }
            public long UnixTimestampMillis { get; set; }
            public static DateTime now() => default!;
            public static DateTime fromUnixTimestamp(long unixTimestamp) => default!;
            public static DateTime fromUnixTimestampMillis(long unixTimestampMillis) => default!;
            public static DateTime fromIsoDate(string isoDate) => default!;
            public string ToIsoDate() => default!;
            public string FormatUniversalTime(string format, string locale) => default!;
            public string FormatLocalTime(string format, string locale) => default!;
        }

        public struct Random
        {
            public Random(int seed) { }
            public double NextNumber() => default!;
            public double NextNumber(double min, double max) => default!;
            public int NextInteger(int min, int max) => default!;
            public Vector3 NextUnitVector() => default!;
            public Random Clone() => default!;
        }

        public struct PhysicalProperties
        {
            public float Density { get; set; }
            public float Friction { get; set; }
            public float Elasticity { get; set; }
            public float FrictionWeight { get; set; }
            public float ElasticityWeight { get; set; }
            public PhysicalProperties(float density, float friction, float elasticity, float frictionWeight, float elasticityWeight) { Density = density; Friction = friction; Elasticity = elasticity; FrictionWeight = frictionWeight; ElasticityWeight = elasticityWeight; }
        }

        public struct Axes
        {
            public bool X { get; set; }
            public bool Y { get; set; }
            public bool Z { get; set; }
        }

        public struct Faces
        {
            public bool Top { get; set; }
            public bool Bottom { get; set; }
            public bool Left { get; set; }
            public bool Right { get; set; }
            public bool Back { get; set; }
            public bool Front { get; set; }
        }

        public struct NumberSequenceKeypoint
        {
            public float Time { get; set; }
            public float Value { get; set; }
            public float Envelope { get; set; }
            public NumberSequenceKeypoint(float time, float value) { Time = time; Value = value; Envelope = default; }
            public NumberSequenceKeypoint(float time, float value, float envelope) { Time = time; Value = value; Envelope = envelope; }
        }

        public struct NumberSequence
        {
            public NumberSequenceKeypoint[] Keypoints { get; set; }
            public NumberSequence(float value) { Keypoints = default!; }
            public NumberSequence(NumberSequenceKeypoint[] keypoints) { Keypoints = keypoints; }
        }

        public struct ColorSequenceKeypoint
        {
            public float Time { get; set; }
            public Color3 Value { get; set; }
            public ColorSequenceKeypoint(float time, Color3 color) { Time = time; Value = color; }
        }

        public struct ColorSequence
        {
            public ColorSequenceKeypoint[] Keypoints { get; set; }
            public ColorSequence(Color3 color) { Keypoints = default!; }
            public ColorSequence(ColorSequenceKeypoint[] keypoints) { Keypoints = keypoints; }
        }

        public struct PathWaypoint
        {
            public Vector3 Position { get; set; }
            public string Label { get; set; }
            public PathWaypoint(Vector3 position) { Position = position; Label = default!; }
        }

        public struct RaycastParams
        {
            public object FilterDescendantsInstances { get; set; }
            public bool IgnoreWater { get; set; }
            public string CollisionGroup { get; set; }
            public bool RespectCanCollide { get; set; }
        }

        // Reference-y datatype: Workspace.Raycast returns it or nil, so model as a class (nullable).
        public class RaycastResult
        {
            public Instance? Instance { get; set; }
            public Vector3 Position { get; set; }
            public Vector3 Normal { get; set; }
            public float Distance { get; set; }
        }

        public struct OverlapParams
        {
            public object FilterDescendantsInstances { get; set; }
            public int MaxParts { get; set; }
            public string CollisionGroup { get; set; }
            public bool RespectCanCollide { get; set; }
        }

        // Opaque handles / less-common datatypes: exist so they map native (Type.new(...)) and never warn.
        public struct CatalogSearchParams { }
        public struct Content { }
        public struct DockWidgetPluginGuiInfo { }
        public struct FloatCurveKey { }
        public struct RotationCurveKey { }
        public struct ValueCurveKey { }
        public struct Path2DControlPoint { }
        public struct SecurityCapabilities { }
        public struct SharedTable { }
        public struct Secret { }
        public struct AdReward { }
        public struct User { }

        public struct RBXScriptConnection
        {
            public bool Connected { get; set; }
            public void Disconnect() { }
        }

        public struct RBXScriptSignal
        {
            public RBXScriptConnection Connect(System.Action callback) => default!;
            public RBXScriptConnection Once(System.Action callback) => default!;
            public void Wait() { }
        }

        public struct RBXScriptSignal<T>
        {
            public RBXScriptConnection Connect(System.Action<T> callback) => default!;
            public RBXScriptConnection Once(System.Action<T> callback) => default!;
            public T Wait() => default!;
        }
        """;

    private static HashSet<string> CollectClassNames(JsonElement root)
    {
        var set = new HashSet<string>();
        if (root.TryGetProperty("Classes", out var classes))
            foreach (var c in classes.EnumerateArray())
                if (c.TryGetProperty("Name", out var n))
                    set.Add(n.GetString()!);
        return set;
    }

    private static void EmitEnum(StringBuilder sb, JsonElement e)
    {
        var name = e.GetProperty("Name").GetString()!;
        sb.AppendLine($"public enum {Safe(name)} : long");
        sb.AppendLine("{");
        var seen = new HashSet<string>();
        if (e.TryGetProperty("Items", out var items))
            foreach (var item in items.EnumerateArray())
            {
                var itemName = item.GetProperty("Name").GetString()!;
                if (!IsIdentifier(itemName) || !seen.Add(itemName))
                    continue;
                sb.AppendLine($"    {Safe(itemName)} = {item.GetProperty("Value").GetInt64()},");
            }
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void EmitClass(StringBuilder sb, JsonElement c, HashSet<string> known)
    {
        var name = c.GetProperty("Name").GetString()!;
        var super = c.TryGetProperty("Superclass", out var s) ? s.GetString() : null;
        var baseClause = super is not null && known.Contains(super) ? $" : {Safe(super)}" : "";

        sb.AppendLine($"public class {Safe(name)}{baseClause}");
        sb.AppendLine("{");

        // Constructor accessibility from the dump: creatable classes -> public (`new Part()` ->
        // Instance.new("Part")); NotCreatable/Service -> protected (blocks `new BasePart()`, still
        // callable as a base ctor by subclasses).
        var creatable = !HasTag(c, "NotCreatable") && !HasTag(c, "Service") && !HasTag(c, "Settings");
        sb.AppendLine($"    {(creatable ? "public" : "protected")} {Safe(name)}() {{ }}");

        var seen = new HashSet<string>();
        if (c.TryGetProperty("Members", out var members))
            foreach (var m in members.EnumerateArray())
                EmitMember(sb, m, known, seen, name);
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void EmitMember(StringBuilder sb, JsonElement m, HashSet<string> known, HashSet<string> seen, string className)
    {
        var kind = m.GetProperty("MemberType").GetString();
        var name = m.GetProperty("Name").GetString()!;
        if (!seen.Add(kind + ":" + name)) // dedupe overloads/dupes (erasure-friendly)
            return;
        if (HasTag(m, "NotScriptable")) // truly unreachable from scripts ("Hidden" is still scriptable)
            return;
        if (!IsIdentifier(name) || name == className) // invalid C# ident, or member == enclosing type name
            return;

        switch (kind)
        {
            case "Property":
                sb.AppendLine($"    public {MapType(m.GetProperty("ValueType"), known)} {Safe(name)} {{ get; set; }} = default!;");
                break;
            case "Function":
                var ret = MapType(m.GetProperty("ReturnType"), known);
                var pars = BuildParams(m, known);
                sb.AppendLine($"    public {ret} {Safe(name)}({pars}) => default!;");
                break;
            case "Event":
                // Event -> a signal property. Single-parameter events are typed RBXScriptSignal<T>.
                var sig = "RBXScriptSignal";
                if (m.TryGetProperty("Parameters", out var eps) && eps.GetArrayLength() == 1)
                    sig = $"RBXScriptSignal<{MapType(eps[0].GetProperty("Type"), known)}>";
                sb.AppendLine($"    public {sig} {Safe(name)} {{ get; }} = default!;");
                break;
        }
    }

    private static string BuildParams(JsonElement m, HashSet<string> known)
    {
        if (!m.TryGetProperty("Parameters", out var ps))
            return "";
        var parts = new List<string>();
        var i = 0;
        foreach (var p in ps.EnumerateArray())
        {
            var pname = p.TryGetProperty("Name", out var pn) ? pn.GetString()! : $"arg{i}";
            parts.Add($"{MapType(p.GetProperty("Type"), known)} {Safe(pname)}");
            i++;
        }
        return string.Join(", ", parts);
    }

    // DataTypes the generator emits, derived from the DataTypes const (single source of truth).
    private static readonly HashSet<string> DataTypeNames =
        System.Text.RegularExpressions.Regex.Matches(DataTypes, @"public (?:struct|class) (\w+)")
            .Select(m => m.Groups[1].Value).ToHashSet();

    private static string MapType(JsonElement t, HashSet<string> known)
    {
        var name = t.TryGetProperty("Name", out var n) ? n.GetString()! : "object";
        var category = t.TryGetProperty("Category", out var c) ? c.GetString() : null;

        if (category == "Enum")
            return Safe(name);
        if (category == "Class" || known.Contains(name))
            return Safe(name) + "?";
        if (category == "DataType" && DataTypeNames.Contains(name))
            return name;

        return name switch
        {
            "string" or "Content" or "ProtectedString" => "string",
            "bool" => "bool",
            "int" => "int",
            "int64" => "long",
            "float" => "float", // Roblox float is 32-bit
            "double" => "double",
            "void" => "void",
            _ => "object",
        };
    }

    private static bool HasTag(JsonElement m, string tag) =>
        m.TryGetProperty("Tags", out var tags) && tags.ValueKind == JsonValueKind.Array
        && tags.EnumerateArray().Any(x => x.GetString() == tag);

    private static bool IsIdentifier(string s)
    {
        if (string.IsNullOrEmpty(s) || !(char.IsLetter(s[0]) || s[0] == '_'))
            return false;
        foreach (var ch in s)
            if (!char.IsLetterOrDigit(ch) && ch != '_')
                return false;
        return true;
    }

    // Escape C# keywords and invalid identifiers.
    private static string Safe(string id)
    {
        if (Keywords.Contains(id))
            return "@" + id;
        return id;
    }

    private static readonly HashSet<string> Keywords = new()
    {
        "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked",
        "class", "const", "continue", "decimal", "default", "delegate", "do", "float", "else",
        "enum", "event", "explicit", "extern", "false", "finally", "fixed", "float", "for",
        "foreach", "goto", "if", "implicit", "in", "int", "interface", "internal", "is", "lock",
        "long", "namespace", "new", "null", "object", "operator", "out", "override", "params",
        "private", "protected", "public", "readonly", "ref", "return", "sbyte", "sealed", "short",
        "sizeof", "stackalloc", "static", "string", "struct", "switch", "this", "throw", "true",
        "try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort", "using", "virtual",
        "void", "volatile", "while",
    };
}
