// Auto-generate the docs sidebar from the docs/ folder tree (intro, examples, api all self-register).
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [{ type: 'autogenerated', dirName: '.' }],
};

module.exports = sidebars;
